(* 月month, 日付dayを受け取って星座を返す *)
(* seiza: int -> int -> string *)
let seiza month day =
  if month = 1 then if 1 <= day && day <= 19 then "山羊座"
		    else if 20 <= day && day <= 31 then "水瓶座"
		    else "なし"
  else if month = 2 then if 1 <= day && day <= 18 then "水瓶座"
		    else if 19 <= day && day <= 29 then "魚座"
		    else "なし"
  else if month = 3 then if 1 <= day && day <= 20 then "魚座"
        else if 21 <= day && day <= 31 then "牡羊座"
		    else "なし"
  else if month = 4 then if 1 <= day && day <= 19 then "牡羊座"
		    else if 20 <= day && day <= 30 then "牡牛座"
		    else "なし"
  else if month = 5 then if 1 <= day && day <= 20 then "牡牛座"
		    else if 21 <= day && day <= 31 then "双子座"
		    else "なし"
  else if month = 6 then if 1 <= day && day <= 21 then "双子座"
		    else if 22 <= day && day <= 30 then "蟹座"
		    else "なし"
  else if month = 7 then if 1 <= day && day <= 22 then "蟹座"
		    else if 23 <= day && day <= 31 then "獅子座"
		    else "なし"
  else if month = 8 then if 1 <= day && day <= 22 then "獅子座"
		    else if 23 <= day && day <= 31 then "乙女座"
		    else "なし"
  else if month = 9 then if 1 <= day && day <= 22 then "乙女座"
		    else if 23 <= day && day <= 30 then "天秤座"
		    else "なし"
  else if month = 10 then if 1 <= day && day <= 23 then "天秤座"
		     else if 24 <= day && day <= 31 then "蠍座"
		     else "なし"
  else if month = 11 then if 1 <= day && day <= 21 then "蠍座"
		     else if 22 <= day && day <= 30 then "射手座"
		     else "なし"
  else if month = 12 then if 1 <= day && day <= 21 then "射手座"
		     else if 22 <= day && day <= 31 then "山羊座"
		     else "なし"
  else "なし"

let test1 = seiza 6 11 = "双子座"
let test2 = seiza 6 30 = "蟹座"
let test3 = seiza 9 17 = "乙女座"
let test4 = seiza 10 7 = "天秤座"
